/**
 * @fileoverview Centralized Error Codes Constants
 */

const ERROR_CODES = {
  DUPLICATE_EMAIL: "DUPLICATE_EMAIL",
  INVALID_INPUT: "INVALID_INPUT",
  WEAK_PASSWORD: "WEAK_PASSWORD",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  TOO_MANY_REQUESTS: "TOO_MANY_REQUESTS",
  BAD_REQUEST: "BAD_REQUEST",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  USER_SUSPENDED: "USER_SUSPENDED",
  USER_DELETED: "USER_DELETED",
  INVALID_SESSION: "INVALID_SESSION",
  TOKEN_REPLAY_DETECTED: "TOKEN_REPLAY_DETECTED",
  INVALID_REFRESH_TOKEN: "INVALID_REFRESH_TOKEN"
};

module.exports = ERROR_CODES;
